project:
  name: "BUILDT Construction"
  description: "The Business Building Site is a comprehensive platform designed to streamline project management and collaboration for businesses. By integrating Source Control Management (SCM) tools and GitHub, the site offers efficient version control, team collaboration, and project tracking, enabling users to manage development workflows seamlessly and enhance productivity."
  technologies:
    - HTML
    - CSS
    - GitHub Pages
  features:
    - Easy to navigate
    - Visually appealing interface
    - Responsive design
    - Hosted using GitHub Pages
  usage:
    instructions:
      - Clone the repository from GitHub
      - Open `index.html` in your browser
      - Explore the interactive sections
  authors:
    - name: "Lakshay Jain"
      role: "HTML and CSS Developers"
    - name: "Jashan Devgan"
      role: "HTML and CSS Developers"
    - name: "Harkirat Singh"
      role: "Project Coordinator"
  repository: "https://github.com/lakshay310/Business-Building-site-SCM-Project.git"
  license: "MIT"
